SELECT	*
FROM	ECLIENT_APLICA_CONCEPTOS
WHERE	CCO_CLICLEF	=	21550 --- * CAMBIAR CLIENTE *
	AND	EXISTS	(
					SELECT	NULL
					FROM	EBASES_POR_CONCEPT
					WHERE	BPCCLAVE		=	CCO_BPCCLAVE
						AND	BPC_CHOCLAVE	IN	(	SELECT	CHOCLAVE 
													FROM	ECONCEPTOSHOJA 
													WHERE	CHOTIPOIE		=	'I' 
														AND	CHONUMERO		=	183 -- CONCEPTO SEGURO DE MERCANCÍA  / NO SE CAMBIA 
														AND	CHO_EMPCLAVE	=	55	-- * CAMBIAR EMPRESA *
												)
				)
;