SELECT
	DISTINCT
		 DIE.DIECODEPOSTAL CODIGO_POSTAL
		,DIL.DEC_CLICLEF NUM_CLIENTE
		,DIE.DIECLAVE DIECLAVE
		,INITCAP( NVL(DIE.DIE_A_ATENCION_DE, DIE.DIENOMBRE) || ' - ' || DIE.DIEADRESSE1 || ' - ' || DIE.DIEADRESSE2 || ' - ' || DER.DER_TIPO_ENTREGA) DIRECCION
		,CIU.VILCLEF CLAVE_CIUDAD, CIU.VILNOM NOMBRE_CIUDAD
		,EST.ESTESTADO CLAVE_ESTADO, EST.ESTNOMBRE NOMBRE_ESTADO
		,NVL(DER.DER_ALLCLAVE, 1) DER_ALLCLAVE
		,CCL.CCL_RFC CCL_RFC
		,CCL.CCLCLAVE CCLCLAVE
        ,DEC_NUM_DIR_CLIENTE
FROM	 EDIRECCION_ENTR_CLIENTE_LIGA	DIL
	INNER JOIN	EDIRECCIONES_ENTREGA	DIE	ON	DIE.DIECLAVE	=	DIL.DEC_DIECLAVE
	INNER JOIN	ECIUDADES				CIU	ON	CIU.VILCLEF		=	DIEVILLE
	INNER JOIN	EESTADOS				EST	ON	EST.ESTESTADO	=	CIU.VIL_ESTESTADO
	INNER JOIN	ECLIENT_CLIENTE			CCL	ON	CCL.CCLCLAVE	=	DIE.DIE_CCLCLAVE
	INNER JOIN	EDESTINOS_POR_RUTA		DER	ON	DER.DER_VILCLEF	=	CIU.VILCLEF
WHERE	1=1
	AND	CCL.CCL_STATUS		=	1
	AND	DIE.DIE_STATUS		=	1
	AND	EST.EST_PAYCLEF		=	'N3'
	AND	DER.DER_ALLCLAVE	>	0
	AND	SF_LOGIS_CLIENTE_RESTRIC(DIL.DEC_CLICLEF, DER.DER_TIPO_ENTREGA)	=	1
	AND	DIL.DEC_CLICLEF		=	'20123'
	--AND	DIE.DIECODEPOSTAL	=	'36700'
ORDER	BY	2,4,1