SELECT	DISTINCT
			DIE.DIECODEPOSTAL CODIGO_POSTAL, EST.ESTESTADO CLAVE_ESTADO, EST.ESTNOMBRE NOMBRE_ESTADO/*, CIU.VILCLEF CLAVE_CIUDAD, CIU.VILNOM NOMBRE_CIUDAD*/
FROM EDIRECCION_ENTR_CLIENTE_LIGA   DIL          
INNER JOIN  EDIRECCIONES_ENTREGA         DIE ON DIE.DIECLAVE = DIL.DEC_DIECLAVE 
INNER JOIN  ECIUDADES                    CIU    ON CIU.VILCLEF = DIEVILLE 
INNER JOIN  EESTADOS                     EST    ON EST.ESTESTADO = CIU.VIL_ESTESTADO        
INNER JOIN  ECLIENT_CLIENTE              CCL    ON CCL.CCLCLAVE = DIE.DIE_CCLCLAVE 
INNER JOIN  EDESTINOS_POR_RUTA           DER    ON DER_VILCLEF = VILCLEF 
WHERE	1=1
    AND	CCL.CCL_STATUS		=	1
    AND	DIE.DIE_STATUS		=	1
    AND	EST.EST_PAYCLEF		=	'N3'
	AND	DER.DER_ALLCLAVE	>	0 
	AND	SF_LOGIS_CLIENTE_RESTRIC(DIL.DEC_CLICLEF, DER.DER_TIPO_ENTREGA)	=	1 
	AND	DIL.DEC_CLICLEF		=	'23488' --'20501'
ORDER	BY	2,1
;