-- Query para generar el archivo excel de reservación de NUI's:
SELECT  LPAD(WTS.NUI, 10, '0') NUMERO_DE_GUIA, '' DESCRIPCION, '' PESO_EN_KG
FROM    WEB_LTL WEL
    INNER JOIN WEB_TRACKING_STAGE WTS ON WEL.WELCLAVE = WTS.NUI
    INNER JOIN WEB_LOTS WL ON WTS.NUMERO_LOTE = WL.LOTE
WHERE 1=1
    --AND WEL.WELSTATUS = 3
    --AND WEL.WEL_CLICLEF = 23632 --23279
    AND WL.LOTE = 9990 --9993--10021----
;