-- Obtiene el Tipo de Tarifa de Distribución que tiene configurada una cuenta, tanto para LTL como para CrossDock:
SELECT	 DISTINCT
		 CCO.CCO_CLICLEF CLIENTE
        ,NVL(PAR.PAR_TIBCLAVE_IMPORTE, PAR.PAR_TIBCLAVE) CLAVE_CALCULO
		,TIB.TIBNOMBRE NOMBRE
--; select distinct NVL(PAR.PAR_TIBCLAVE_IMPORTE, PAR.PAR_TIBCLAVE) CLAVE_CALCULO,TIB.TIBNOMBRE NOMBRE
FROM	 ECLIENT_APLICA_CONCEPTOS CCO
	INNER	JOIN	EBASES_POR_CONCEPT BPC	ON	CCO.CCO_BPCCLAVE	=	BPC.BPCCLAVE
	INNER	JOIN	EPARAMETRO_RESTRICT PAR	ON	BPC.BPC_PARCLAVE	=	PAR.PARCLAVE
	INNER	JOIN	ETIPO_BASE_TARIFA TIB	ON	NVL(PAR.PAR_TIBCLAVE_IMPORTE, PAR.PAR_TIBCLAVE)	=	TIB.TIBCLAVE
WHERE	1 = 1
	AND	CCO.CCO_CLICLEF		=	'23220'
    --AND	CCO.CCO_CLICLEF		in	('23149','23221','23217')
    --AND	CCO.CCO_CLICLEF		IN	(20120,20459,23149,23150,23058,20150,20287,22916,7956,20689,20480,20501,17873,13203)
    --AND NVL(PAR.PAR_TIBCLAVE_IMPORTE, PAR.PAR_TIBCLAVE) IN (231,234)
	AND	BPC.BPC_CHOCLAVE	IN	(
									SELECT	CHO.CHOCLAVE
									FROM	ECONCEPTOSHOJA CHO
									WHERE	1 = 1
										/*	40	DISTRIBUCION CROSS DOCK	*/
										/*	172	DISTRIBUCION LTL		*/
										AND	CHO.CHONUMERO		IN	(40,172)
										AND	CHO.CHO_EMPCLAVE	IN	(
																		SELECT	LIGA.CET_EMPCLAVE CVE_EMPRESA
																		FROM	ECLIENT_EMPRESA_TRADING LIGA
																		WHERE	1 = 1
																			AND	LIGA.CET_CLICLEF	=	CCO.CCO_CLICLEF
																	)
								)
ORDER	BY 1
;