SELECT	LOCLOGIN
	, LOCPASSWORD
    , CLICLEF
    , (SELECT DSUSUARIO FROM (
        SELECT rownum numero,DSUSUARIO FROM USUARIOS) t WHERE numero =
        abs(extract(month from sysdate) + extract(day from sysdate) 
        + to_number(to_char(sysdate,'HH24')) 
        + to_number(to_char(sysdate,'mm')) - to_number(to_char(sysdate,'ss'))
        )) AS CLICLEF_PWD
	, CLINOM || DECODE(CLIALIAS, NULL, NULL, ' - ' || CLIALIAS)
	, DECODE(LCD_CLICLEF, LOCCLIENTE,'CHECKED') AS CHECKED
	, CLISTATUS
	, LOCSTATUS
	, NVL(LOCDESCRIPCION, CLINOM)
	, LCD_DISCLEF
	, LCD_ALLCLAVE
	, NVL(UPPER(LCD_WEL_OBSERVACION),UPPER(LOGIS.GET_CLI_LTL_OBSERVACIONES(CLICLEF)) LCD_WEL_OBSERVACION) OBSERVACION
	, (SELECT COUNT(0) FROM ECLIENT_MODALIDADES WHERE CLM_CLICLEF = CLICLEF AND CLM_MOECLAVE = 29)
	, (SELECT COUNT(0) FROM ECLIENT_MODALIDADES WHERE CLM_CLICLEF = CLICLEF AND CLM_MOECLAVE = 33)
FROM	ELOGINCLIENTE
	, ELOGINCLIENTEDETALLE
	, ECLIENT
WHERE	LOCLOGIN(+) = LCD_LOCLOGIN
    AND	UPPER(LOCLOGIN) LIKE UPPER('%20123%')
    --AND CLICLEF = 21501
    --AND UPPER(LOCPASSWORD) = UPPER('wvD32tdc4')
	AND	CLICLEF = LCD_CLICLEF(+)
ORDER BY LOCLOGIN, CHECKED;