/*   REPROCESAR PEDIMENTOS DE ANTOLIN   */

-- 1.- OBTENER EL CLIENTE AL QUE CORRESPONDE EL PEDIMENTO Y EL SGECLAVE QUE SE V A REPROCESAR:
SELECT * FROM ESAAI_M3_GENERAL WHERE SGEPEDNUMERO = '3420-1009337'  AND SGEDOUCLEF = 24;
-- SGE_CLICLEF 18870
-- SGECLAVE 2932757,2933244,2941243,2941432,2941855,2942043

 
 -- 2.- QUERY QUE OBTIENE LOS DODA's:
 SELECT COUNT(0) DODAS ,SGE.SGECLAVE,FOL.FOL_CLICLEF
  FROM EDOCUMENTOS_SAT  DSA  
       , EFOLIOS        FOL  
       , ECLIENT        CLI  
       , EDOCUMENTO_ANEXO DAX  
       , ECATALOGO_ANEXOS CAX  
       , EPEDIMENTO PED  
       , ESAAI_M3_GENERAL SGE  
  WHERE SGE.SGECLAVE in (2932757,2933244,2941243,2941432,2941855,2942043)
  AND SGE.SGEPEDNUMERO = PED.PEDNUMERO  
  AND SGE.SGEDOUCLEF = PED.PEDDOUANE  
  AND SGE.SGEANIO = PED.PEDANIO  
  AND PED.PEDFOLIO = FOL.FOLCLAVE  
  AND FOL.FOL_CLICLEF = CLI.CLICLEF  
  AND DSA.DSA_FOLCLAVE = FOL.FOLCLAVE 
  AND (DSA.DSA_SGECLAVE IS NULL OR DSA.DSA_SGECLAVE = SGE.SGECLAVE) 
  AND DSAEDOCUMENT_MANUAL = 'N'   
  AND DAX.DAXCLAVE = DSA.DSA_DAXCLAVE  
  AND CAX.CAXCLAVE = DAX.DAX_CAXCLAVE  
  AND CAX.CAXCLAVE = 186
GROUP BY SGE.SGECLAVE,FOL.FOL_CLICLEF;
/*   NOTA: Si no se encuentran DODA's, se envía un correo como "Report  Expediente Antolin 18870 sin DODA"   */


-- 3.- OBTENER EL ID DEL REPORTE:
SELECT * FROM REP_REPORTE WHERE COMMAND = 'pedim_pdf_doda';
    --  ID_REP: 326

-- 4.- OBTENER EL ID_CRON PARA USARLO EN EL PROYECTO DE VB6:
SELECT * FROM REP_DETALLE_REPORTE WHERE ID_REP = 326 AND CLIENTE = 18870;
    --  ID_CRON: 7046066	--5307259
	--	ID_CRON: 6380349	-- cliente: 20020
    
 
-- 5.- QUERY QUE OBTIENE LOS PEDIMENTOS DESDE VB:
SELECT DISTINCT SGECLAVE,SGEPEDNUMERO,SGEDOUCLEF,SGEANIO,SGE_ADUANA_SECCION,FOLFOLIO  ,DATE_CREATED,SGEFECHA_PAGO
FROM ( 
 SELECT NULL EGECLAVE 
      , SGE.SGECLAVE SGECLAVE 
      , SGE.SGEPEDNUMERO SGEPEDNUMERO 
      , SGE.SGEDOUCLEF SGEDOUCLEF 
      , SGE.SGEANIO SGEANIO 
      , NVL(SGE.SGE_ADUANA_SECCION, '0') SGE_ADUANA_SECCION 
      , FOL.FOLFOLIO FOLFOLIO 
      , SGE.DATE_CREATED DATE_CREATED 
      , SGE.SGEFECHA_PAGO SGEFECHA_PAGO 
   FROM ESAAI_M3_GENERAL SGE 
       ,EPEDIMENTO PED 
       ,EFOLIOS FOL 
  WHERE 1 = 1 
     AND SGE.SGE_CLICLEF = 18870 
    and PED.PEDNUMERO = '3420-1007292' 
    and SGE.SGEDOUCLEF = '47' 
    AND PED.PEDNUMERO = SGE.SGEPEDNUMERO 
    AND PED.PEDDOUANE = SGE.SGEDOUCLEF 
    AND PED.PEDANIO = SGE.SGEANIO 
    AND FOL.FOLCLAVE = PED.PEDFOLIO 
    AND SGE.SGEFIRMA_ELECTRONICA IS NOT NULL 
    AND SGE.SGEFECHA_PAGO < TRUNC(SYSDATE) - 1 
    AND NOT EXISTS (SELECT NULL 
                      FROM TB_LOGIS_EXP_GEN EGE 
                     WHERE EGE.EGE_SGECLAVE = SGE.SGECLAVE 
                    ) 
 UNION ALL 
 SELECT EGE.EGECLAVE EGECLAVE 
      , EGE.EGE_SGECLAVE SGECLAVE 
      , SGE.SGEPEDNUMERO SGEPEDNUMERO 
      , SGE.SGEDOUCLEF SGEDOUCLEF 
      , SGE.SGEANIO SGEANIO 
      , NVL(SGE.SGE_ADUANA_SECCION, '0') SGE_ADUANA_SECCION 
      , FOL.FOLFOLIO FOLFOLIO 
      , SGE.DATE_CREATED DATE_CREATED 
      , SGE.SGEFECHA_PAGO SGEFECHA_PAGO 
   FROM TB_LOGIS_EXP_GEN EGE 
      , ESAAI_M3_GENERAL SGE  
      , EPEDIMENTO PED 
      , EFOLIOS FOL 
  WHERE SGE.SGECLAVE = EGE.EGE_SGECLAVE 
     AND SGE.SGE_CLICLEF = 18870 
    and PED.PEDNUMERO = '3420-1007292' 
    and SGE.SGEDOUCLEF = '47' 
    AND PED.PEDNUMERO = SGE.SGEPEDNUMERO 
    AND PED.PEDDOUANE = SGE.SGEDOUCLEF 
    AND PED.PEDANIO = SGE.SGEANIO 
    AND FOL.FOLCLAVE = PED.PEDFOLIO 
    ) 
ORDER BY 4, 2;

 
-- EL CÓDIGO EN VB INSERTA EN ÉSTAS TABLAS:
SELECT * FROM rep_detalle_reporte WHERE id_cron = 5307259;
SELECT * FROM REP_CHRON WHERE ID_RAPPORT = 5307259;


-- SQL_CLAVE_PEDTOS
SELECT DISTINCT EGECLAVE FROM ( 
 SELECT NULL EGECLAVE  
   FROM ESAAI_M3_GENERAL SGE 
       ,EPEDIMENTO PED 
       ,EFOLIOS FOL 
  WHERE SGE.SGE_CLICLEF = 18870
    AND PED.PEDNUMERO = SGE.SGEPEDNUMERO 
    AND PED.PEDDOUANE = SGE.SGEDOUCLEF 
    AND PED.PEDANIO = SGE.SGEANIO 
    AND FOL.FOLCLAVE = PED.PEDFOLIO 
    AND SGE.SGEFECHA_PAGO >= TRUNC(SYSDATE) - 2 
    AND SGE.SGEFIRMA_ELECTRONICA IS NOT NULL 
    AND SGE.SGEFECHA_PAGO < TRUNC(SYSDATE) - 1 
    AND NOT EXISTS (SELECT NULL 
                      FROM TB_LOGIS_EXP_GEN EGE 
                     WHERE EGE.EGE_SGECLAVE = SGE.SGECLAVE 
--                       AND EGE.EGESTATUS = 'E' 
                    ) 
 UNION ALL 
 SELECT EGE.EGECLAVE EGECLAVE 
   FROM TB_LOGIS_EXP_GEN EGE 
      , ESAAI_M3_GENERAL SGE  
      , EPEDIMENTO PED 
      , EFOLIOS FOL 
  WHERE SGE.SGECLAVE = EGE.EGE_SGECLAVE 
    AND EGE.EGE_CLICLEF = 18870
    AND PED.PEDNUMERO = SGE.SGEPEDNUMERO 
    AND PED.PEDDOUANE = SGE.SGEDOUCLEF 
    AND PED.PEDANIO = SGE.SGEANIO 
    AND FOL.FOLCLAVE = PED.PEDFOLIO 
--    AND EGE.EGESTATUS = 'P' 
 ) T 
 ORDER BY 1;






SELECT  *
FROM    REP_DETALLE_REPORTE
WHERE   ID_REP  =   311
    AND   (
            NAME LIKE '%3420-2002254%'  --  7044341
        OR  NAME LIKE '%3420-2005344%'  --  7044344
        OR  NAME LIKE '%3420-2005496%'  --  7044345
        OR  NAME LIKE '%3744-2000279%'  --  7047545
        )
ORDER   BY 1 DESC;